{ lib }:

let
  # 统一调色板：深色基于 catppuccin-mocha (与 waybar/swaync/anyrun 旧静态 fallback 一致)
  # 浅色基于 catppuccin-latte 派生，对齐 light.niri 的品牌色 #1e66f5
  palettes = {
    dark = {
      background = "rgba(20, 20, 28, 0.85)";
      backgroundCard = "rgba(30, 30, 42, 0.88)";
      foreground = "#cdd6f4";
      foregroundMuted = "#a6adc8";
      foregroundDim = "#6c7086";
      border = "rgba(255, 255, 255, 0.08)";
      activeBorder = "#89b4fa";
      accent = "#89b4fa";
      hoverBg = "rgba(255, 255, 255, 0.08)";
      hoverBgLight = "rgba(255, 255, 255, 0.12)";
      selectedBg = "rgba(137, 180, 250, 0.15)";
      glow = "rgba(137, 180, 250, 0.35)";
      warning = "#f9e2af";
      critical = "#f38ba8";
    };
    light = {
      background = "rgba(239, 241, 245, 0.85)";
      backgroundCard = "rgba(230, 233, 239, 0.88)";
      foreground = "#4c4f69";
      foregroundMuted = "#6c6f85";
      foregroundDim = "#8c8fa1";
      border = "rgba(76, 79, 105, 0.12)";
      activeBorder = "#1e66f5";
      accent = "#1e66f5";
      hoverBg = "rgba(76, 79, 105, 0.08)";
      hoverBgLight = "rgba(76, 79, 105, 0.12)";
      selectedBg = "rgba(30, 102, 245, 0.12)";
      glow = "rgba(30, 102, 245, 0.35)";
      warning = "#df8e1d";
      critical = "#d20f39";
    };
  };

  # 将 palette 转为 GTK CSS @define-color 块 (waybar/swaync/anyrun 共享超集)
  # 包含 waybar 的 8 色 + swaync 扩展的 muted/dim/hover-light/selected-bg/accent + anyrun 兼容别名与 glow
  toCss = palette: ''
    @define-color background ${palette.background};
    @define-color background-card ${palette.backgroundCard};
    @define-color foreground ${palette.foreground};
    @define-color foreground-muted ${palette.foregroundMuted};
    @define-color foreground-dim ${palette.foregroundDim};
    @define-color border-color ${palette.border};
    @define-color active-border ${palette.activeBorder};
    @define-color accent ${palette.accent};
    @define-color hover-bg ${palette.hoverBg};
    @define-color hover-bg-light ${palette.hoverBgLight};
    @define-color selected-bg ${palette.selectedBg};
    @define-color glow-color ${palette.glow or "alpha(@accent, 0.35)"};
    @define-color warning ${palette.warning};
    @define-color critical ${palette.critical};

    /* Anyrun 语义别名 */
    @define-color bg-color ${palette.background};
    @define-color card-bg ${palette.backgroundCard};
    @define-color fg-color ${palette.foreground};
    @define-color desc-color ${palette.foregroundMuted};
  '';

  # 生成运行时 colors.css 内容 (含文件头注释)
  generateColorsCss = mode:
    let
      palette = palettes.${mode} or palettes.dark;
    in
    ''
      /* desktop-theme unified colors — ${mode} — generated by theme-switch.sh */
      ${toCss palette}
    '';

in
{
  inherit palettes toCss generateColorsCss;
}
