[
  # 常见 Qt / KDE / Polkit 框架应用与系统对话框微调
  "float, class:^(org.fcitx.fcitx5-config-qt)$"
  "center, class:^(org.fcitx.fcitx5-config-qt)$"
  "size 850 600, class:^(org.fcitx.fcitx5-config-qt)$"
  "float, class:^(qt5ct|qt6ct|kvantummanager)$"
  "center, class:^(qt5ct|qt6ct|kvantummanager)$"
  "size 850 650, class:^(qt5ct|qt6ct|kvantummanager)$"
  "float, class:^(pavucontrol|org.pulseaudio.pavucontrol)$"
  "center, class:^(pavucontrol|org.pulseaudio.pavucontrol)$"
  "size 800 600, class:^(pavucontrol|org.pulseaudio.pavucontrol)$"
  "float, class:^(nm-connection-editor|nm-applet)$"
  "center, class:^(nm-connection-editor|nm-applet)$"
  "size 750 550, class:^(nm-connection-editor|nm-applet)$"
  "float, class:^(blueman-manager)$"
  "center, class:^(blueman-manager)$"
  "size 750 550, class:^(blueman-manager)$"
  "float, class:^(pinentry-.*|pinentry)$"
  "center, class:^(pinentry-.*|pinentry)$"
  "pin, class:^(pinentry-.*|pinentry)$"
  "stayfocused, class:^(pinentry-.*|pinentry)$"
  "float, class:^(polkit-.*|org.kde.polkit-kde-authentication-agent-1|lxqt-policykit)$"
  "center, class:^(polkit-.*|org.kde.polkit-kde-authentication-agent-1|lxqt-policykit)$"
  "stayfocused, class:^(polkit-.*|org.kde.polkit-kde-authentication-agent-1|lxqt-policykit)$"
  "float, class:^(kdialog)$, title:^(.*)$"

  # 常见跨框架文件选择、保存与进度对话框
  "float, title:^(Open File|Select a File|Choose Files|Open Folder|Save As|Save File|All Files|另存为|打开文件|选择文件|打开文件夹|保存文件)$"
  "center, title:^(Open File|Select a File|Choose Files|Open Folder|Save As|Save File|All Files|另存为|打开文件|选择文件|打开文件夹|保存文件)$"
  "size 900 600, title:^(Open File|Select a File|Choose Files|Open Folder|Save As|Save File|All Files|另存为|打开文件|选择文件|打开文件夹|保存文件)$"
  "float, title:^(File Upload|Upload Files|文件上传)$"
  "float, title:^(Confirm to replace files|File Operation Progress|文件操作进度|替换文件)$"
]
